[build]
  command = "npm install && npm run build"  # ✅ Ensures full build process
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # ✅ Keep this for optimized function bundling

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
