[build]
  command = "npm install && npm run build"  # ✅ Ensures full build process
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # ✅ Keep this for optimized function bundling
  included_files = ["netlify/functions/hubspot.js"]  # ✅ Ensures hubspot.js is deployed
  environment = { HUBSPOT_API_KEY = "HUBSPOT_API_KEY" }  # ✅ Ensure HubSpot API key is available in Netlify functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
